public class calculationss {
    public decimal subtract(decimal x, decimal y){
        decimal Total = x-y;
        system.debug('Total decimal '+Total);
        return total;
    }
    public static integer multiply(integer y, integer z){
        integer sum= y*z;
        system.debug('total multiple sum = '+sum);
        return sum;
    }
    public static string concate(string FirstName, string LastName){
      return FirstName+' '+LastName;
    }
 
}